name: simple_mip_solver
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - cython
  - pkg-config
  - scipy
  - future
  - gurobi
  - numpy
  - pandas
  - pip
  - python
  - pip:
    - coinor-cuppy
    - coverage
